# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OzmLpQP54akJGyzvuIOcG3coFGJCzez
"""

import time
import matrix_ops as mo

A = mo.make_matrix(3, 3)
B = mo.make_matrix(3, 3)
v = mo.make_vector(3)

print("матрица A:", A)
print("матрица B:", B)
print("вектор v:", v)

print("A*B:", mo.mat_mul(A, B))
print("A*v:", mo.mat_vec_mul(A, v))
print("след A:", mo.diag_sum(A))
print("скалярное v*v:", mo.dot(v, v))
print("гистограмма v (5 бинов):", mo.histogram(v, 5))
print("фильтр v ядром [-1,0,1]:", mo.filter_vector(v, [-1, 0, 1]))

mo.write_data("data.txt", A)
print("прочитано из файла:", mo.read_data("data.txt"))

# замеры времени
results = []

for n in [10, 50, 100, 200]:
    A = mo.make_matrix(n, n)
    B = mo.make_matrix(n, n)
    v = mo.make_vector(n)
    kernel1d = [-1, 0, 1]
    kernel2d = mo.make_matrix(3, 3)

    t0 = time.time()
    mo.mat_mul(A, B)
    t1 = time.time()
    results.append(("mat_mul", n, t1 - t0))

    t0 = time.time()
    mo.mat_vec_mul(A, v)
    t1 = time.time()
    results.append(("mat_vec_mul", n, t1 - t0))

    t0 = time.time()
    mo.diag_sum(A)
    t1 = time.time()
    results.append(("diag_sum", n, t1 - t0))

    t0 = time.time()
    mo.dot(v, v)
    t1 = time.time()
    results.append(("dot", n, t1 - t0))

    t0 = time.time()
    mo.histogram(v, 10)
    t1 = time.time()
    results.append(("histogram", n, t1 - t0))

    t0 = time.time()
    mo.filter_vector(v, kernel1d)
    t1 = time.time()
    results.append(("filter_vector", n, t1 - t0))

    t0 = time.time()
    mo.convolution_2d(A, kernel2d)
    t1 = time.time()
    results.append(("convolution_2d", n, t1 - t0))

# сохраняем замеры в файл
with open("timing.txt", "w") as f:
    f.write("function n time\n")
    for name, n, t in results:
        f.write(f"{name} {n} {t:.6f}\n")

print("результаты замеров сохранены в timing.txt")
for name, n, t in results:
    print(f"{name:15s} n={n:4d}  {t:.6f} сек")